name: Validate JSON

on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  json_validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: JSON Schema Validation
      uses: OrRosenblatt/validate-json-action@v1
      with:
        schema: './v1/schema.json'
        jsons: '["./data/user.json"]'
